import notfound from '../assets/notfound.png'

export const defaultImg = (): string => notfound;

export const countries = [
    { id: 1, value: 'ar', label: 'Argentina' },
    { id: 2, value: 'au', label: 'Australia' },
    { id: 3, value: 'at', label: 'Austria' },
    { id: 4, value: 'be', label: 'Belgium' },
    { id: 5, value: 'br', label: 'Brazil' },
    { id: 6, value: 'bg', label: 'Bulgaria' },
    { id: 7, value: 'ca', label: 'Canada' },
    { id: 8, value: 'cn', label: 'China' },
    { id: 9, value: 'co', label: 'Colombia' },
    { id: 10, value: 'cu', label: 'Cuba' },
    { id: 11, value: 'cz', label: 'Czech Republic' },
    { id: 12, value: 'eg', label: 'Egypt' },
    { id: 13, value: 'fr', label: 'France' },
    { id: 14, value: 'de', label: 'Germany' },
    { id: 15, value: 'gr', label: 'Greece' },
    { id: 16, value: 'hk', label: 'Hongkong' },
    { id: 17, value: 'hu', label: 'Hungaria' },
    { id: 18, value: 'in', label: 'India' },
    { id: 19, value: 'id', label: 'Indonesia' },
    { id: 21, value: 'ie', label: 'Ireland' },
    { id: 22, value: 'il', label: 'Israel' },
    { id: 23, value: 'it', label: 'Italia' },
    { id: 24, value: 'jp', label: 'Japan' },
    { id: 25, value: 'lv', label: 'Latvia' },
    { id: 26, value: 'lt', label: 'Lithuania' },
    { id: 27, value: 'my', label: 'Malaysia' },
    { id: 28, value: 'mx', label: 'Mexico' },
    { id: 29, value: 'ma', label: 'Morocco' },
    { id: 30, value: '', label: 'Netherlands' },
    { id: 31, value: 'nz', label: 'New Zealand' },
    { id: 32, value: 'ng', label: 'Nigeria' },
    { id: 33, value: 'no', label: 'Norway' },
    { id: 34, value: 'ph', label: 'Philippines' },
    { id: 35, value: 'pl', label: 'Poland' },
    { id: 36, value: 'pt', label: 'Portugal' },
    { id: 37, value: 'ro', label: 'Romania' },
    { id: 38, value: 'ru', label: 'Rusia' },
    { id: 39, value: 'sa', label: 'Saudi Arabia' },
    { id: 40, value: 'rs', label: 'Serbia' },
    { id: 41, value: 'sg', label: 'Singapore' },
    { id: 42, value: 'si', label: 'Slovenia' },
    { id: 43, value: 'za', label: 'South Africa' },
    { id: 44, value: 'kr', label: 'South Korea' },
    { id: 45, value: 'se', label: 'Sweden' },
    { id: 46, value: 'ch', label: 'Switzerland' },
    { id: 47, value: 'tw', label: 'Taiwan' },
    { id: 48, value: 'th', label: 'Thailand' },
    { id: 49, value: 'tr', label: 'Turkey' },
    { id: 50, value: 'ae', label: 'UAE' },
    { id: 51, value: 'ua', label: 'Ukraine' },
    { id: 52, value: 'gb', label: 'United Kingdom' },
    { id: 53, value: 'us', label: 'United States' },
    { id: 54, value: 've', label: 'Venezuela' },
]

export const categories = [
    { id: 1, value: 'business', label: 'Business' },
    { id: 2, value: 'entertainment', label: 'Entertainment' },
    { id: 3, value: 'general', label: 'General' },
    { id: 4, value: 'health', label: 'Health' },
    { id: 5, value: 'science', label: 'Science' },
    { id: 6, value: 'sport', label: 'Sport' },
    { id: 7, value: 'techonology', label: 'Techonology' },
]